global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # This is for Prometheus itself

  # Example of a valid target
  - job_name: 'fov_api'
    static_configs:
      - targets: ['fov_api:8080']  # Update to match your actual service and port
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']   # Replace with your ASP.NET Core app endpoint exposing metrics

