name: Deploy

on:
  push:
    branches: [ docker_config ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
        timeout: 60s
        script: |
          cd /home/vktrng/deployment/
          
          # Remove old directory if it exists
          if [ -d ./FOV-Fall2024-API ]; then
            echo "Removing old project directory..."
            rm -rf FOV-Fall2024-API
          fi

          # Clone the latest version from the docker_config branch
          git clone --branch docker_config https://github.com/FOV-Fall2024/FOV-Fall2024-API.git
          cd FOV-Fall2024-API
          
          # List files to verify successful clone
          ls -al
          
          # Bring up the Docker container
          docker-compose --project-name fov up -d
