name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          port: 2222
          timeout: 60s
          script: |
            cd /home/vktrng/

            if [ -d ./FOV-Fall2024-API ]; then
              echo "Directory exists. Pulling latest changes..."
              cd ./FOV-Fall2024-API
              git reset --hard
              git pull origin main
            else
              echo "Cloning the repository..."
              git clone https://github.com/FOV-Fall2024/FOV-Fall2024-API.git
              cd FOV-Fall2024-API
            fi

            echo "Stopping and removing old containers..."
            make remove

            echo "Building and starting containers..."
            make all

            echo "Rebuilding specific services if needed..."
            make update

            echo "Stopping database container for maintenance..."
            docker ps | grep -q fov_database && docker stop fov_database
