name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          timeout: 60s
          script: |
            cd /home/vktrng/

            if [ -d ./FOV-Fall2024-API ]; then
              docker-compose -f FOV-Fall2024-API/docker-compose.yml down
              cd ./FOV-Fall2024-API
              git pull origin main
              make build
              make commit
            else
              echo "Cloning the repository..."
              git clone https://github.com/FOV-Fall2024/FOV-Fall2024-API.git
              cd FOV-Fall2024-API
            fi
            docker-compose build fov.presentation
            docker-compose --project-name fov up -d
            
            sleep 1m
            docker stop fov_database
